### ISSUE TITLE
Database not working / is empty

### ISSUE THREAD

**Issue by ahnaf000** [motapinto/football-classification-predications#1]
Hey, I and a friend of mine are trying to use your model to predict the outcomes of competitive soccer games. 
However, when we try to run your code, we get an error while reading from the database. After some debugging, we realized that the database is actually empty. 
Can the authors help us fix that problem, please?

**Comment by motapinto** [comment]
Hey! Just updated the notebook and after a quick test in google colab it seems it's working again. 
You will need a Kaggle account and edit one of the initial cells to add your Kaggle username and API token.
Please check it and let me know if you got any more issues.
